// poolResolver.js
// Maps every pool code used in the degree plans to its label, hours, and list of valid course codes.
//
// The pools are data: src/data/pools.json, generated by `npm run build:catalog` from the prototype repo's
// degree-specs/pools.json (see its README). Each pool is an explicit course list, a rule over the catalog
// (resolved to a list at build time), Flight Foundations' published gen-ed list (kept in flightFoundations.js),
// or open (any course). Nothing about a pool is written in this file, so a new major's pools need no code change.
//
// Each key is a pool code that appears as class_code in requirement_slots where is_pool = true.
// Each POOL_COURSES value is an array of course codes valid for that slot, or null for an open pool.

import { listFlightFoundationsCourses } from './flightFoundations.js'
import POOL_DEFS from '../data/pools.json'

const membersOf = def => {
  if (def.kind === 'source') return listFlightFoundationsCourses(def.category)
  if (def.kind === 'open') return null
  return def.courses
}

// Order is the order of pools.json: resolveSatisfiesPool takes the first pool on a plan that lists a course.
export const POOL_COURSES = Object.fromEntries(Object.entries(POOL_DEFS).map(([code, def]) => [code, membersOf(def)]))

// A course that every option of the pool needs first: the degree builder never places the pool's slots before it.
export const POOL_FLOORS = Object.fromEntries(Object.entries(POOL_DEFS).filter(([, def]) => def.floor).map(([code, def]) => [code, def.floor]))

// Gen-ed pools whose options are specific courses a required course can
// depend on — CSC3040 needs COMM2025 or PC2500, which only the COMM_REQ slot
// provides. Elective pools are left out: a slot that can hold any CSC course
// isn't a meaningful prerequisite, and CSC1200 (a CSC_ELECTIVE option) in
// CSC1300's prereqs would tie CSC1300 to a pool that must follow CSC1310.
// Listed in the order they take open seats when interleaving (Step 11).
// Also the pools an unfilled slot can stand in for when checking prereqs.
export const REQUIREMENT_POOLS = new Set(
  Object.entries(POOL_DEFS).filter(([, def]) => def.gates).sort(([, a], [, b]) => a.gates - b.gates).map(([code]) => code),
)

// ── Pool slot display labels ──────────────────────────────────────────────────
// Single source of truth shared by Semester (slot row) and SlotModal (modal title).

export const POOL_LABELS = Object.fromEntries(Object.entries(POOL_DEFS).map(([code, def]) => [code, def.label]))

// ── Pool slot credit estimates ────────────────────────────────────────────────
// Expected hours for a pool slot the student hasn't filled yet (a slot's own
// flex_credits takes precedence). Shared by the degree builder, which balances
// semesters with them, and standing checks, which count an unfilled slot as
// the hours it will carry.

export const POOL_CREDIT_ESTIMATES = Object.fromEntries(Object.entries(POOL_DEFS).map(([code, def]) => [code, def.credits]))

// ── Pool limits and notes ─────────────────────────────────────────────────────
// A pool may carry `limits`: rules about the picks across all its slots, from the catalog ("at most 3 hours of these count as
// Area of Emphasis"; "at least 9 of the 15 hours from the ME list", written as at most 6 from outside it). A limit is
// { label, why, maxHours, courses | except }: it counts the hours of the picks inside `courses`, or of every pick outside
// `except`. And a `note`: what the app cannot check (an approval) shown with the pool. Both come from pools.json.

export const POOL_LIMITS = Object.fromEntries(Object.entries(POOL_DEFS).filter(([, def]) => def.limits?.length).map(([code, def]) => [code, def.limits]))
export const POOL_NOTES  = Object.fromEntries(Object.entries(POOL_DEFS).filter(([, def]) => def.note).map(([code, def]) => [code, def.note]))

const inLimit = (limit, code) => (limit.courses ? limit.courses.includes(code) : !limit.except.includes(code))

// The courses chosen in a pool's active slots: [{ slotId, code, hours }] (hours as the student's plan counts them)
function poolPicks(poolCode, planSlots, slots, courses, planArchived) {
  return slots
    .filter(s => s.is_pool && s.class_code === poolCode && !planArchived[s.id] && planSlots[s.id])
    .map(s => ({ slotId: s.id, code: planSlots[s.id], hours: courses[planSlots[s.id]]?.credits ?? POOL_CREDIT_ESTIMATES[poolCode] ?? 0 }))
}

/**
 * Which picks break a limit of their pool: { [slotId]: [{ label, why, hours, maxHours }] }. Every pick the limit counts
 * is flagged, so the student sees which slots add up to too many hours.
 */
export function getPoolLimitWarnings(planSlots, slots, courses, planArchived = {}) {
  const out = {}
  for (const [poolCode, limits] of Object.entries(POOL_LIMITS)) {
    const picks = poolPicks(poolCode, planSlots, slots, courses, planArchived)
    for (const limit of limits) {
      const counted = picks.filter(p => inLimit(limit, p.code))
      const hours = counted.reduce((sum, p) => sum + p.hours, 0)
      if (hours <= limit.maxHours) continue
      for (const p of counted) (out[p.slotId] ??= []).push({ label: limit.label, why: limit.why, hours, maxHours: limit.maxHours })
    }
  }
  return out
}

/**
 * The message for the first limit that choosing `candidate` for this slot would break, or null. The slot's own current pick
 * is replaced, not added.
 */
export function limitBrokenByPick(slot, candidate, planSlots, slots, courses, planArchived = {}) {
  const limits = POOL_LIMITS[slot.class_code]
  if (!limits) return null
  const others = poolPicks(slot.class_code, planSlots, slots, courses, planArchived).filter(p => p.slotId !== slot.id)
  for (const limit of limits) {
    if (!inLimit(limit, candidate.code)) continue
    const hours = others.filter(p => inLimit(limit, p.code)).reduce((sum, p) => sum + p.hours, 0) + (candidate.credits ?? 0)
    if (hours > limit.maxHours) return limit.why
  }
  return null
}

// ── Helper function ───────────────────────────────────────────────────────────
// Given a pool code and the full course catalog (as the courseMap object
// from DegreePlan), returns an array of course objects valid for that slot.
// Returns null for an open pool (FREE_ELECTIVE, Nuclear Engineering's Area of Emphasis) — the modal handles that case separately.

// ── resolveSatisfiesPool ──────────────────────────────────────────────────────
// Given a transfer-credit course code and the active concentration's
// requirement_slots, return the pool code (e.g. 'CSC_ELECTIVE') that the
// transfer should archive, or null if no pool on this plan contains it.
//
// BUG-4: CSC2220 belongs to both CSC_LOWER_ELECTIVE and CSC_ELECTIVE, so a
// concentration-agnostic scan over POOL_COURSES always returned the first
// match and missed the real slot on Cybersecurity/DSAI plans (which have
// CSC_ELECTIVE slots but no CSC_LOWER_ELECTIVE slots). Scoping to the pools
// that actually appear as is_pool slots on the active plan fixes this.

export function resolveSatisfiesPool(courseCode, slots) {
  if (!courseCode) return null
  const planPoolCodes = new Set(
    (slots ?? [])
      .filter(s => s?.is_pool)
      .map(s => s.class_code)
  )
  for (const [poolCode, codes] of Object.entries(POOL_COURSES)) {
    if (!planPoolCodes.has(poolCode)) continue
    if (codes?.includes(courseCode)) return poolCode
  }
  return null
}

// ── mapSatisfiesPoolForPlan ───────────────────────────────────────────────────
// test_equivalencies rows name the legacy pool an exam credit fills ('GEN_ED').
// A Flight Foundations plan has no GEN_ED slots — the same course fills
// FF_SOCIAL / FF_HUMANITIES or a fixed History slot — so the pool is resolved
// against the pools the plan actually has.  Every other pool (SCIENCE, ENG_LIT,
// …) exists in both programs and passes through unchanged, as does any pool on a
// plan that still has GEN_ED slots.

export function mapSatisfiesPoolForPlan(poolCode, courseCode, slots) {
  if (poolCode !== 'GEN_ED') return poolCode
  const hasGenEd = (slots ?? []).some(s => s?.is_pool && s.class_code === 'GEN_ED')
  if (hasGenEd || !slots?.length) return poolCode
  return resolveSatisfiesPool(courseCode, slots)
}

export function resolvePool(poolCode, courseMap) {
  // an open pool (pools.json "open") — return null to signal open resolution
  // (handled separately in SlotModal with suggestions)
  if (poolCode === 'FREE_ELECTIVE' || POOL_COURSES[poolCode] === null) return null

  const codes = POOL_COURSES[poolCode]
  if (!codes) return []

  return codes
    .filter(code => courseMap[code])
    .map(code => courseMap[code])
}

// ── resolveScience ────────────────────────────────────────────────────────────

export const SCIENCE_SEQUENCES = [
  { courses: ['CHEM1110', 'CHEM1120'] },
  { courses: ['PHYS2010', 'PHYS2020'] },
  { courses: ['PHYS2110', 'PHYS2120'] },
  { courses: ['GEOL1040', 'GEOL1045'] },
  { courses: ['BIOL1123', 'BIOL1113'] },
  { courses: ['BIOL2310', 'BIOL1113'] },
]

export function resolveScience(planSlots, slots, courseMap) {
  const scienceSlotIds = slots
    .filter(s => s.is_pool && s.class_code === 'SCIENCE')
    .map(s => s.id)

  const selectedScienceCodes = scienceSlotIds
    .map(id => planSlots[id])
    .filter(Boolean)

  if (selectedScienceCodes.length === 0) return { mode: 'normal' }

  // BIOL1113 narrows to its two valid partners — but only if neither
  // partner has been selected yet. Once a partner is filled, the biology
  // sequence is covered and the modal falls through to the normal pool.
  if (selectedScienceCodes.includes('BIOL1113')) {
    const partnerSelected = selectedScienceCodes.includes('BIOL1123')
      || selectedScienceCodes.includes('BIOL2310')
    if (!partnerSelected) {
      return {
        mode: 'narrow',
        courses: ['BIOL1123', 'BIOL2310']
          .filter(c => courseMap[c])
          .map(c => courseMap[c]),
      }
    }
    return { mode: 'normal' }
  }

  // Find a sequence whose courses contain every already-selected code.
  // If found and there is a missing member, autofill it; otherwise the
  // sequence is already complete (or no single sequence covers the
  // selection — e.g. two codes from different sequences) → normal.
  for (const seq of SCIENCE_SEQUENCES) {
    const allInSeq = selectedScienceCodes.every(c => seq.courses.includes(c))
    if (!allInSeq) continue
    const missing = seq.courses.find(c => !selectedScienceCodes.includes(c))
    if (missing && courseMap[missing]) {
      return { mode: 'autofill', course: courseMap[missing] }
    }
    break
  }

  return { mode: 'normal' }
}

// ── getScienceWarnings ────────────────────────────────────────────────────────
// Given the current planSlots and the full slots list, returns a map of
// { [slotId]: { type: 'incomplete'|'conflict', sequenceName?: string } }
// describing any science-sequence problems that should be shown on the degree
// plan grid (not in the modal).
//
// Rules:
//   • Both empty         → no warnings
//   • One filled, one empty → warn on the empty slot: must complete the sequence
//   • Both filled, same sequence → no warnings (plan is valid)
//   • Both filled, different sequences → conflict warning on BOTH slots

const SCIENCE_SEQUENCE_NAMES = {
  'CHEM1110': 'Chemistry',
  'CHEM1120': 'Chemistry',
  'PHYS2010': 'Physics (Algebra)',
  'PHYS2020': 'Physics (Algebra)',
  'PHYS2110': 'Physics (Calculus)',
  'PHYS2120': 'Physics (Calculus)',
  'GEOL1040': 'Geology',
  'GEOL1045': 'Geology',
  'BIOL1113': 'Biology',
  'BIOL1123': 'Biology',
  'BIOL2310': 'Biology',
}

export function getScienceWarnings(planSlots, slots) {
  const scienceSlots = slots.filter(s => s.is_pool && s.class_code === 'SCIENCE')
  if (scienceSlots.length < 2) return {}

  const warnings = {}
  const known = c => Object.prototype.hasOwnProperty.call(SCIENCE_SEQUENCE_NAMES, c)

  // Iterate every pair of SCIENCE slots so 3+ slot configurations are handled.
  // For 2 slots this reduces to one iteration with the original behavior.
  for (let i = 0; i < scienceSlots.length; i++) {
    for (let j = i + 1; j < scienceSlots.length; j++) {
      const slotA = scienceSlots[i]
      const slotB = scienceSlots[j]
      const codeA = planSlots[slotA.id]
      const codeB = planSlots[slotB.id]

      // Both filled — invalid iff the pair is not in any SCIENCE_SEQUENCES entry.
      if (codeA && codeB) {
        if (known(codeA) && known(codeB)) {
          const validPair = SCIENCE_SEQUENCES.some(
            s => s.courses.includes(codeA) && s.courses.includes(codeB)
          )
          if (!validPair) {
            warnings[slotA.id] = { type: 'conflict' }
            warnings[slotB.id] = { type: 'conflict' }
          }
        }
        continue
      }

      // One filled, one empty — warn the empty slot to complete the sequence.
      // First match wins per slot; later pairs do not overwrite an existing
      // warning on the same empty slot.
      if (codeA && !codeB && !warnings[slotB.id]) {
        const seqName = SCIENCE_SEQUENCE_NAMES[codeA]
        if (seqName) warnings[slotB.id] = { type: 'incomplete', sequenceName: seqName }
      } else if (!codeA && codeB && !warnings[slotA.id]) {
        const seqName = SCIENCE_SEQUENCE_NAMES[codeB]
        if (seqName) warnings[slotA.id] = { type: 'incomplete', sequenceName: seqName }
      }
    }
  }

  return warnings
}

// ── GEN_ED sub-requirement categories ────────────────────────────────────────
// Each category requires at least 6 credit hours.
// Course codes here must exactly match those listed in POOL_COURSES.GEN_ED above.

// Note: HIST2010 and HIST2020 are independent — no ordering required between them.
export const GEN_ED_CATEGORIES = {
  History: [
    'HIST2010',
    'HIST2020',
  ],
  Humanities: [
    'ART1035',
    'ART2000',
    'ART2020',
    'FLST2520',
    'FLST3520',
    'FREN2510',
    'GERM2520',
    'HIST1310',
    'HIST2210',
    'HIST2220',
    'HIST2310',
    'HIST2320',
    'MUS1030',
    'PHIL1030',
    'PHIL2250',
    'RELS2010',
    'SPAN2510',
    'SPAN2550',
    'THEA1030',
  ],
  Social: [
    'AGBE2010',
    'ANTH1100',
    'ECON2010',
    'ECON2020',
    'ESS1100',
    'EXPW2015',
    'GEOG1012',
    'GEOG1130',
    'JOUR1110',
    'POLS1030',
    'PSY1030',
    'SOC1010',
    'WGS2010',
  ],
}

// ── getGenEdStatus ────────────────────────────────────────────────────────────
// Returns an array of three objects — one per sub-category — describing how
// many credit hours the student has filled toward the 6-hr minimum and whether
// they are at risk of being unable to meet a sub-requirement.
//
// "At risk" means the total credits still needed across all three categories
// exceeds the capacity of the remaining empty GEN_ED slots.  When the overall
// plan becomes infeasible every unsatisfied category is flagged.
//
// Archived slots are NOT capacity (BUG-54).  A slot archived by a prior credit
// is gone from the grid, so counting it as an open seat overstates how much
// room is left and silences the at-risk warning exactly when it matters most:
// a student whose prior credits saturate two sub-pools has fewer seats left
// than unarchived-slot arithmetic suggests.  Callers pass the same
// planArchived map the grid filters on.
//
// Shape: [{ category, label, filled, required, satisfied, atRisk }, ...]

const GEN_ED_CATEGORY_LABELS = {
  History:   'History',
  Humanities: 'Humanities & Arts',
  Social:    'Social Science',
}

export function getGenEdStatus(planSlots, slots, courseMap, priorCredits = [], planArchived = {}) {
  const genEdSlots  = slots.filter(
    s => s.is_pool && s.class_code === 'GEN_ED' && !planArchived?.[s.id]
  )
  const emptySlots  = genEdSlots.filter(s => !planSlots[s.id]).length

  // Build a reverse lookup: courseCode → category
  const codeToCategory = {}
  for (const [cat, codes] of Object.entries(GEN_ED_CATEGORIES)) {
    for (const code of codes) codeToCategory[code] = cat
  }

  // Sum credits per category from filled GEN_ED slots
  const creditsByCategory = { History: 0, Humanities: 0, Social: 0 }
  for (const slot of genEdSlots) {
    const code = planSlots[slot.id]
    if (!code) continue
    const cat = codeToCategory[code]
    if (cat) {
      creditsByCategory[cat] += courseMap[code]?.credits ?? 3
    }
  }

  // Sum credits per category from prior credits (BUG-45)
  for (const pc of (priorCredits ?? [])) {
    if ((pc.credits_awarded ?? 0) <= 0) continue
    if (!pc.satisfies_course_code) continue
    const cat = codeToCategory[pc.satisfies_course_code]
    if (cat) creditsByCategory[cat] += pc.credits_awarded
  }

  const REQUIRED = 6

  // Total credits still needed across all categories
  const totalShortfall = Object.values(creditsByCategory).reduce((sum, filled) => {
    return sum + Math.max(0, REQUIRED - filled)
  }, 0)

  // If the remaining empty slots can't cover the combined shortfall, every
  // unsatisfied category is at risk.
  const overallAtRisk = totalShortfall > emptySlots * 3

  return ['History', 'Humanities', 'Social'].map(cat => {
    const filled    = creditsByCategory[cat]
    const satisfied = filled >= REQUIRED
    const atRisk    = !satisfied && overallAtRisk
    return {
      category:  cat,
      label:     GEN_ED_CATEGORY_LABELS[cat],
      filled,
      required:  REQUIRED,
      satisfied,
      atRisk,
    }
  })
}

// ── formatMissingForDisplay ───────────────────────────────────────────────────
// BUG-37: Rewrites the `missing` array returned by checkPrereqs/checkCoreqs
// into a freshman-readable string.  Pool members inside an OR group collapse
// to the pool's display label so "Needs: COMM2025, PC2500" reads as
// "Needs: Communications" — codes outside any pool stay verbatim.
//
// Input shape (per prereqChecker.js):
//   - bare code:      'CSC1300'
//   - OR group:       '(A or B or C)'
//
// Rules for OR groups:
//   - For each pool that has 2+ codes in this group, replace those codes
//     with POOL_LABELS[poolCode]. A single pool member alone is NOT
//     collapsed — the prereq genuinely names that one course.
//   - Tie-break across pools: the pool with the most matching codes wins;
//     ties resolve to Object.entries iteration order on POOL_COURSES.
//   - The output OR group joins remaining tokens with ' or '.  When the
//     group reduces to a single token, drop the parentheses entirely.

export function formatMissingForDisplay(missing) {
  if (!Array.isArray(missing) || missing.length === 0) return ''
  return missing.map(formatOne).join(', ')
}

function formatOne(entry) {
  if (typeof entry !== 'string') return String(entry)
  const m = entry.match(/^\((.+)\)$/)
  if (!m) return entry                                    // bare code
  const codes = m[1].split(' or ').map(s => s.trim()).filter(Boolean)
  if (codes.length <= 1) return entry                     // malformed — leave alone

  let chosenPool    = null
  let chosenMembers = null
  for (const [poolCode, poolList] of Object.entries(POOL_COURSES)) {
    if (!Array.isArray(poolList)) continue                // skip FREE_ELECTIVE (null)
    const owned = codes.filter(c => poolList.includes(c))
    // A pool a course can depend on is the better name when two pools list the same courses (ME 4020 / ME 4720 are in both
    // Machine or Thermal Design and the Area of Emphasis list).
    const better = chosenMembers && owned.length === chosenMembers.length && REQUIREMENT_POOLS.has(poolCode) && !REQUIREMENT_POOLS.has(chosenPool)
    if (owned.length >= 2 && (!chosenMembers || owned.length > chosenMembers.length || better)) {
      chosenPool    = poolCode
      chosenMembers = owned
    }
  }

  if (!chosenPool) return entry

  const remaining = codes.filter(c => !chosenMembers.includes(c))
  const tokens    = [POOL_LABELS[chosenPool], ...remaining]
  if (tokens.length === 1) return tokens[0]
  return `(${tokens.join(' or ')})`
}

// ── getGenEdSubCategory ───────────────────────────────────────────────────────
// Returns { category, label } for any GEN_ED course code, or null if the code
// is not a GEN_ED member.  Used by SlotModal section grouping (BUG-43) and by
// PriorCreditWizard Step 4 to label which sub-pool an awarded credit fills.

export function getGenEdSubCategory(courseCode) {
  if (!courseCode) return null
  for (const [category, codes] of Object.entries(GEN_ED_CATEGORIES)) {
    if (codes.includes(courseCode)) {
      return { category, label: GEN_ED_CATEGORY_LABELS[category] }
    }
  }
  return null
}

// ── resolveFreeElective ───────────────────────────────────────────────────────

export function resolveFreeElective(courseMap, slots, planSlots) {
  const planSubjectCodes = new Set()

  slots
    .filter(s => !s.is_pool)
    .forEach(s => {
      const course = courseMap[s.class_code]
      if (course) planSubjectCodes.add(course.subject_code)
    })

  Object.values(planSlots).forEach(code => {
    const course = courseMap[code]
    if (course) planSubjectCodes.add(course.subject_code)
  })

  const allCourses = Object.values(courseMap)

  const suggested = allCourses
    .filter(c => planSubjectCodes.has(c.subject_code))
    .sort((a, b) => a.code.localeCompare(b.code))

  const other = allCourses
    .filter(c => !planSubjectCodes.has(c.subject_code))
    .sort((a, b) => a.code.localeCompare(b.code))

  return { suggested, other }
}

// Drops courses already planned or taken (a Set of codes) from a
// resolveFreeElective result. A free elective can't repeat a course the plan
// already holds; the picker hides them rather than greying them out.
export function excludeFreeElectiveCodes({ suggested, other }, excludeCodes) {
  const keep = c => !excludeCodes.has(c.code)
  return { suggested: suggested.filter(keep), other: other.filter(keep) }
}